const words = {
    easy: [
        "the", "and", "for", "you", "not", "but", "all", "any", "can", "had",
        "her", "was", "one", "our", "out", "day", "get", "has", "him", "his",
        "how", "man", "new", "now", "old", "see", "two", "way", "who", "boy",
        "cat", "dog", "sun", "moon", "star", "sky", "run", "jump", "walk", "play",
        "red", "blue", "green", "pink", "black", "white", "hat", "cup", "pen", "box",
        "toy", "ball", "tree", "leaf", "rain", "snow", "wind", "fire", "rock", "sand",
        "fish", "bird", "frog", "duck", "cow", "pig", "goat", "milk", "cake", "rice",
        "book", "page", "read", "draw", "sing", "song", "dance", "smile", "laugh", "cry",
        "bed", "door", "wall", "room", "home", "road", "car", "bike", "bus", "ship",
        "shoe", "sock", "coat", "cap", "ring", "bell", "coin", "key", "lock", "map",
        "apple", "pear", "plum", "grape", "lemon", "peach", "berry", "melon", "corn",
        "egg", "meat", "soup", "salt", "sugar", "honey", "bread", "cheese", "butter",
        "ice", "cold", "hot", "warm", "cool", "fast", "slow", "big", "small", "tall",
        "short", "thin", "thick", "round", "flat", "soft", "hard", "loud", "quiet",
        "yes", "no", "ok", "hey", "wow", "fun", "win", "lose", "try", "fail",
        "safe", "risk", "help", "care", "love", "hate", "like", "need", "want",
        "open", "close", "push", "pull", "lift", "drop", "catch", "throw", "hit",
        "cut", "fix", "make", "break", "build", "clean", "dirty", "wet", "dry",
        "dark", "light", "early", "late", "near", "far", "up", "down", "left", "right",
        "top", "bottom", "side", "front", "back", "inside", "outside"
    ],
    medium: [
        "people", "family", "friend", "animal", "planet", "nature", "future", "school",
        "teacher", "student", "lesson", "subject", "history", "science", "maths", "music",
        "language", "country", "city", "village", "street", "market", "office", "company",
        "worker", "leader", "member", "player", "winner", "loser", "creator", "builder",
        "machine", "engine", "system", "network", "computer", "tablet", "screen", "camera",
        "picture", "image", "photo", "design", "pattern", "project", "process", "result",
        "problem", "solution", "answer", "example", "method", "option", "choice", "chance",
        "moment", "period", "minute", "second", "morning", "evening", "holiday", "weekend",
        "weather", "climate", "season", "summer", "winter", "autumn", "spring", "storm",
        "thunder", "lightning", "rainbow", "sunrise", "sunset", "mountain", "valley",
        "forest", "desert", "island", "ocean", "river", "stream", "waterfall", "beach",
        "animal", "insect", "reptile", "mammal", "creature", "habitat", "shelter",
        "energy", "power", "motion", "force", "speed", "gravity", "matter", "element",
        "oxygen", "carbon", "metal", "plastic", "rubber", "cotton", "fabric", "leather",
        "clothes", "jacket", "trousers", "shoes", "fashion", "style", "mirror", "window",
        "kitchen", "bathroom", "garden", "garage", "balcony", "hallway", "furniture",
        "table", "chair", "cabinet", "drawer", "pillow", "blanket", "curtain", "carpet",
        "travel", "journey", "ticket", "passport", "luggage", "airport", "station",
        "vehicle", "traffic", "engine", "battery", "signal", "control", "button",
        "gaming", "console", "player", "avatar", "mission", "level", "score", "reward",
        "coding", "program", "software", "website", "browser", "internet", "server",
        "account", "profile", "password", "security", "privacy", "message", "comment",
        "social", "network", "channel", "content", "creator", "viewer", "subscriber",
        "fitness", "exercise", "running", "jumping", "stretch", "balance", "strength",
        "healthy", "diet", "vitamin", "protein", "sleep", "rest", "energy", "focus"
    ],
    hard: [
        "information", "development", "environment", "understanding", "relationship",
        "intelligence", "opportunity", "communication", "responsibility", "organization",
        "professional", "achievement", "imagination", "productivity", "independence",
        "confidence", "motivation", "discipline", "creativity", "collaboration",
        "leadership", "management", "strategy", "planning", "evaluation", "analysis",
        "research", "investigation", "observation", "experiment", "hypothesis",
        "technology", "innovation", "automation", "computation", "architecture",
        "infrastructure", "optimization", "integration", "implementation",
        "sustainability", "biodiversity", "ecosystem", "conservation", "restoration",
        "atmosphere", "temperature", "precipitation", "circulation", "adaptation",
        "manufacturing", "distribution", "transportation", "logistics", "operation",
        "efficiency", "performance", "scalability", "reliability", "maintenance",
        "encryption", "authentication", "authorization", "vulnerability", "cybersecurity",
        "regulation", "legislation", "governance", "jurisdiction", "compliance",
        "philosophy", "psychology", "sociology", "anthropology", "linguistics",
        "neuroscience", "cognition", "perception", "behavior", "emotion",
        "economics", "macroeconomics", "microeconomics", "inflation", "investment",
        "entrepreneurship", "competition", "globalization", "capitalization",
        "architecture", "engineering", "construction", "urbanization", "modernization",
        "transportation", "electrification", "telecommunication", "digitalization",
        "visualization", "representation", "interpretation", "classification",
        "standardization", "prioritization", "coordination", "administration",
        "negotiation", "mediation", "arbitration", "litigation", "jurisprudence",
        "epidemiology", "immunization", "rehabilitation", "diagnostics", "therapeutics",
        "biotechnology", "genomics", "proteomics", "metabolism", "homeostasis",
        "astrophysics", "cosmology", "astronomy", "gravitational", "electromagnetic",
        "quantitative", "qualitative", "probability", "statistical", "correlation",
        "simulation", "virtualization", "augmentation", "optimization", "parallelism",
        "synchronization", "interoperability", "compatibility", "configuration",
        "documentation", "specification", "verification", "validation", "benchmarking",
        "transformation", "disruption", "acceleration", "consolidation", "diversification"
    ]
};
